{"name": "test_JoinUs_using_Letter_BnNumber", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <TRADO.QA_WEB.Utils.utils_QA.Utils object at 0x00000131521A1A50>, expected = 'abcd', actual = ''\n\n    @allure.step\n    @allure.description('This validation method, if the assert failed it will take screenshot')\n    def assertion(self, expected, actual):\n        driver = self.driver\n        try:\n>           assert expected == actual\nE           AssertionError\n\n..\\Utils\\utils_QA.py:15: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <TRADO.QA_WEB.Tests.testQA_Business_interface.TestQA_Business_Interface_Chrome1 object at 0x00000131518EDC00>\n\n    @pytest.mark.sanity\n    @allure.description('Successfully Join using letter BnNumber input')\n    @allure.severity(allure.severity_level.NORMAL)\n    def test_JoinUs_using_Letter_BnNumber(self):\n        driver = self.driver\n        join = Business_Interface_Page(driver)\n        join.Click_Business_Interface_Box()\n        join.Enter_FirstName_box('team')\n        join.Enter_LastName_Box('two')\n>       join.Enter_BnNumber_box('abcd')\n\ntestQA_Business_interface.py:127: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\Pages\\businessInterfaceQA_page.py:52: in Enter_BnNumber_box\n    Utils(self.driver).assertion(BnNumber, BnNumber_input.get_attribute('value'))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <TRADO.QA_WEB.Utils.utils_QA.Utils object at 0x00000131521A1A50>, expected = 'abcd', actual = ''\n\n    @allure.step\n    @allure.description('This validation method, if the assert failed it will take screenshot')\n    def assertion(self, expected, actual):\n        driver = self.driver\n        try:\n            assert expected == actual\n            self.driver.implicitly_wait(1000)\n    \n        except AssertionError:\n            allure.attach(driver.get_screenshot_as_png(), name='screenShot',attachment_type=AttachmentType.PNG)\n>           raise AssertionError\nE           AssertionError\n\n..\\Utils\\utils_QA.py:20: AssertionError"}, "description": "Successfully Join using letter BnNumber input", "steps": [{"name": "Click_Business_Interface_Box", "status": "passed", "start": 1677091247308, "stop": 1677091248419}, {"name": "Enter_FirstName_box", "status": "passed", "steps": [{"name": "assertion", "status": "passed", "parameters": [{"name": "expected", "value": "'team'"}, {"name": "actual", "value": "'team'"}], "start": 1677091248512, "stop": 1677091248514}], "parameters": [{"name": "First_Name", "value": "'team'"}], "start": 1677091248419, "stop": 1677091248516}, {"name": "Enter_LastName_Box", "status": "passed", "steps": [{"name": "assertion", "status": "passed", "parameters": [{"name": "expected", "value": "'two'"}, {"name": "actual", "value": "'two'"}], "start": 1677091248590, "stop": 1677091248592}], "parameters": [{"name": "Last_Name", "value": "'two'"}], "start": 1677091248516, "stop": 1677091248593}, {"name": "Enter_BnNumber_box", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"C:\\Users\\user\\QA_Automation\\2023_Final_Project\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\user\\QA_Automation\\2023_Final_Project\\TRADO\\QA_WEB\\Pages\\businessInterfaceQA_page.py\", line 52, in Enter_BnNumber_box\n    Utils(self.driver).assertion(BnNumber, BnNumber_input.get_attribute('value'))\n  File \"C:\\Users\\user\\QA_Automation\\2023_Final_Project\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\user\\QA_Automation\\2023_Final_Project\\TRADO\\QA_WEB\\Utils\\utils_QA.py\", line 20, in assertion\n    raise AssertionError\n"}, "steps": [{"name": "assertion", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"C:\\Users\\user\\QA_Automation\\2023_Final_Project\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\user\\QA_Automation\\2023_Final_Project\\TRADO\\QA_WEB\\Utils\\utils_QA.py\", line 20, in assertion\n    raise AssertionError\n"}, "attachments": [{"name": "screenShot", "source": "acf8b8a8-1963-4f04-8678-bd74fc63da3d-attachment.png", "type": "image/png"}], "parameters": [{"name": "expected", "value": "'abcd'"}, {"name": "actual", "value": "''"}], "start": 1677091248655, "stop": 1677091248818}], "parameters": [{"name": "BnNumber", "value": "'abcd'"}], "start": 1677091248593, "stop": 1677091248818}], "attachments": [{"name": "stdout", "source": "905e7313-38b5-4357-9e74-534620d9a996-attachment.txt", "type": "text/plain"}], "start": 1677091247307, "stop": 1677091248819, "uuid": "d3dc8d4c-86ce-47c8-acbe-9f1103d21d6a", "historyId": "665084bbe1df2e2ef83d77e900f751cb", "testCaseId": "30d50f9daef80d51bd38a7051512f0ff", "fullName": "testQA_Business_interface.TestQA_Business_Interface_Chrome1#test_JoinUs_using_Letter_BnNumber", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "sanity"}, {"name": "tag", "value": "@pytest.mark.usefixtures('Valid_Login_With_login_Code')"}, {"name": "suite", "value": "testQA_Business_interface"}, {"name": "subSuite", "value": "TestQA_Business_Interface_Chrome1"}, {"name": "host", "value": "LAPTOP-42FB6NAB"}, {"name": "thread", "value": "20332-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testQA_Business_interface"}]}